# Generated by Django 3.1.4 on 2020-12-30 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'verbose_name': 'Новость', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AddField(
            model_name='articles',
            name='company',
            field=models.CharField(default='', max_length=20, verbose_name='Название компании'),
        ),
    ]
